### ISSUE TITLE
help codespell ignore words

### ISSUE THREAD

**Issue by magland** [NeurodataWithoutBorders/lindi#100]
@yarikoptic How do I tell codespell to ignore certain words? I thought it was the -L option, but that doesn't seem to work. See the gh action. It's this PR that is causing trouble:

#99

**Comment by yarikoptic** [comment]
add them to `ignore-words-list` which you uncomment here:

https://github.com/NeurodataWithoutBorders/lindi/blob/main/pyproject.toml#L36

e.g.

```
ignore-words-list = 'tempory,someotherprecious'
```

it will be case insensitive and needs to be lower case
