### ISSUE TITLE
expand use of templates

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/lindi#65]
I see from https://github.com/NeurodataWithoutBorders/lindi/pull/51 that we now support using templates for URLs that appear many times.

The [RFS template language v1](https://fsspec.github.io/kerchunk/spec.html#version-1) also supports using an iterator to generate dataset regions. This could be very helpful in minimizing JSON files that map to a large number of chunks.

**Comment by magland** [comment]
Thanks @bendichter 

This works well when there is a template-able sequence of offsets (e.g. regular intervals), and it doesn't save as much space in the usual case where the offsets and sizes vary without a pattern across all the chunks.

**Comment by bendichter** [comment]
Oh, is it often the case that chunks are not along regular intervals? Is this because compression reduced each chunk by a different amount?

**Comment by bendichter** [comment]
I suppose this would work well if data is chunked but not compressed, but that might not come up that often

**Comment by magland** [comment]
> Oh, is it often the case that chunks are not along regular intervals? Is this because compression reduced each chunk by a different amount?

Yes, that's right.
