### ISSUE TITLE
Discuss library name

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/lindi#7]
The README currently defines the name as Linked Neurodata Interface (LINDI). I'm wondering how specific the library actually will be to neurodata. It seems this library may be much more broad in nature, in that it only cares about the data format (HDF5, Zarr, etc.) but it may not really care about the actual schema. Dealing with the schema and application-specific functions, seem like they will likely remain with the domain libraries, e.g,. PyNWB, HDMF etc.. With that in mind (and keeping with the current acronym), I'm wondering whether it should be just **Lin**ked **D**ata **I**nterface (LINDI).

**Comment by rly** [comment]
I like Linked Data Interface, but I worry that it will be overly broad and connected to JSON-LD. We are really interfacing between chunked array storage.  How about **Li**nked **N**-**D**imensional Array **I**nterface (LINDI)?

**Comment by rly** [comment]
Some other options that didn't quite make the cut:
- Linked Interoperable Neurophysiology Data Initiative (LINDI)
- Linked Integrated Neurophysiology Data Initiative (LINDI)
- Modular Interfaces for Neurophysiology Data Integration (MINDI)
- Scheme for Integrating Multi-dimensional Blocks of Arrays (SIMBA)
- Scheme for Organizing Distributed Arrays (SODA)
- Modular Neurophysiology Data Organization (MONDO)
- Modular Data Linking Scheme (MODALS)
- Flexible Linked Data Scheme (FIELDS)
- Scheme for Integrating Linked N-Dimensional Arrays
- Scheme for Integrating N-dimensional Arrays (SINA)
- Scheme for Accessing Distributed N-Dimensional Arrays (SADNA)
- Distributed Array Data Scheme (DADS)
- Integration of Distributed Arrays (INDA)
- Linked Approach to Multi-dimensional Blocks of Data Arrays (LAMBDA) 
- Scheme for Accessing Distributed Arrays (SADA)
- Integration of Distributed Arrays
- Unified Access to Distributed Arrays
- Distributed Organization of N-Dimensional Arrays (DONA)
- Modular Organization of N-Dimensional Arrays (MONDA)
- Modular Array Dataset

**Comment by magland** [comment]
Or zarrbie :)

**Comment by magland** [comment]
Or we could call it LINDI and have it stand for multiple things, depending on the context.

**Comment by magland** [comment]
Distributed Archives for Neurophysiology Data Integration = DANDI
Linked Neurophysiology Data Interface = LINDI

and then when it's not neurophysiology

Linked Data Interface

**Comment by oruebel** [comment]
So far, my personal favorites are:

- Linked Data Interface (LINDI)
- Linked Array Data Interface (LADI)
- Interface for Linked Array Data (iLAD)

**Comment by rly** [comment]
All right, let's go with Linked Data Interface (LINDI). It's growing on me.
